# Generated by Django 5.2.7 on 2025-11-01 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis', models.CharField(help_text='Primary diagnosis (ICD-10 code)', max_length=200)),
                ('medication_name', models.CharField(help_text='Medication name', max_length=200)),
                ('additional_diagnoses', models.TextField(blank=True, help_text='Additional diagnoses (comma-separated ICD-10 codes)')),
                ('medication_history', models.TextField(blank=True, help_text='Medication history (comma-separated list)')),
                ('patient_records', models.TextField(help_text='Full patient medical history and clinical notes (max 50,000 chars)', max_length=50000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Patient's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Patient's last name", max_length=100)),
                ('mrn', models.CharField(help_text='Medical Record Number (6 digits)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mrn', message='MRN must be exactly 6 digits', regex='^\\d{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provider's full name", max_length=200)),
                ('npi', models.CharField(help_text='National Provider Identifier (10 digits)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_npi', message='NPI must be exactly 10 digits', regex='^\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_plan_text', models.TextField(help_text='Full care plan generated by LLM')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='care_plans.order')),
            ],
            options={
                'verbose_name': 'Care Plan',
                'verbose_name_plural': 'Care Plans',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(help_text='Patient for this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='care_plans.patient'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(help_text='Referring provider', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='care_plans.provider'),
        ),
    ]
