# Generated by Django 5.2.7 on 2025-11-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
