from django.db import models
from django.core.validators import RegexValidator


class Provider(models.Model):
    """
    Healthcare provider (doctor, specialist, etc.)

    Business Rule: NPI must be unique across the system to ensure accurate
    pharma reporting and prevent duplicate provider entries.
    """
    name = models.CharField(
        max_length=200,
        help_text="Provider's full name"
    )
    npi = models.CharField(
        max_length=10,
        unique=True,
        validators=[RegexValidator(
            regex=r'^\d{10}$',
            message='NPI must be exactly 10 digits',
            code='invalid_npi'
        )],
        help_text="National Provider Identifier (10 digits)"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} (NPI: {self.npi})"

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Provider"
        verbose_name_plural = "Providers"


class Patient(models.Model):
    """
    Patient in the pharmacy system

    Business Rule: MRN (Medical Record Number) uniquely identifies each patient.
    """
    first_name = models.CharField(
        max_length=100,
        help_text="Patient's first name"
    )
    last_name = models.CharField(
        max_length=100,
        help_text="Patient's last name"
    )
    mrn = models.CharField(
        max_length=6,
        unique=True,
        validators=[RegexValidator(
            regex=r'^\d{6}$',
            message='MRN must be exactly 6 digits',
            code='invalid_mrn'
        )],
        help_text="Medical Record Number (6 digits)"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} (MRN: {self.mrn})"

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Patient"
        verbose_name_plural = "Patients"


class Order(models.Model):
    """
    Care plan order/request submitted by pharmacist

    Links patient, provider, and clinical information needed to generate
    a care plan for Medicare reimbursement and pharma reporting.
    """
    # Relationships
    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        related_name='orders',
        help_text="Patient for this order"
    )
    provider = models.ForeignKey(
        Provider,
        on_delete=models.CASCADE,
        related_name='orders',
        help_text="Referring provider"
    )

    # Clinical information
    primary_diagnosis = models.CharField(
        max_length=200,
        help_text="Primary diagnosis (ICD-10 code)"
    )
    medication_name = models.CharField(
        max_length=200,
        help_text="Medication name"
    )

    # Store as text (comma-separated or JSON strings)
    # Trade-off: Simpler schema vs. harder to query individual items
    # Decision: Simpler is better for prototype, all data goes to LLM anyway
    additional_diagnoses = models.TextField(
        blank=True,
        help_text="Additional diagnoses (comma-separated ICD-10 codes)"
    )
    medication_history = models.TextField(
        blank=True,
        help_text="Medication history (comma-separated list)"
    )

    # Full clinical notes for LLM
    patient_records = models.TextField(
        max_length=50000,
        help_text="Full patient medical history and clinical notes (max 50,000 chars)"
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order #{self.id} - {self.patient.mrn} - {self.medication_name}"

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Order"
        verbose_name_plural = "Orders"


class CarePlan(models.Model):
    """
    AI-generated care plan for an order

    One-to-one relationship: Each order has exactly one care plan.
    Stores the full care plan text generated by Claude LLM.
    """
    order = models.OneToOneField(
        Order,
        on_delete=models.CASCADE,
        related_name='care_plan',
        help_text="Associated order"
    )
    care_plan_text = models.TextField(
        help_text="Full care plan generated by LLM"
    )
    generated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Care Plan for Order #{self.order.id}"

    class Meta:
        ordering = ['-generated_at']
        verbose_name = "Care Plan"
        verbose_name_plural = "Care Plans"
